accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import register

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/', register, name='register')
]

dstagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from .views import *

app_name='photo'

urlpatterns = [
    path('', PhotoListView.as_view(), name='photo_list'),
    path('detail/<int:pk>/',PhotoDetailView.as_view(), name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
]

accounts/models.py
from django.db import models

# Create your models here.

photo/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Photo(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_photos')   # ForeignKey값을 이용하여 User 테이블과 이어줌 on_delete인수는 연결된 모델이 삭제될 경우 현제 모델값의 처리를 결정
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default='photos/no_image.png')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)                                       #auto_now_add는 객체가 추가될 때 자동으로 값을 설정
    updated = models.DateTimeField(auto_now=True)                                           #auto_now 수정될때마다
    
    class Meta:
        ordering = ['-updated']                                                             #모델의 객체들 정렬 기준

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=[str(self.id)])                           # 객체의 상세 페이지의 주소를 변환하는 메소드. 객체를 추가하거나 수정했을 때 이동할 주소를 위해 호출

accounts/forms.py
from django.contrib.auth.models import User
from django import forms

class RegisterForm(forms.ModelForm):                                                     #ModelForm상속
    password = forms.CharField(label='Password', widget=forms.PasswordInput)            #password-> Meta class 안 fields에서 설정가능하지만 CharField이기 때문에 widget옵션을사용해 지정
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:                                                                         #기존에 있는 모델의 입력 폼
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):                                                          #유효성 검사 메소드 ->password와 password2가 같은지 검사
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords not matched!')
        return cd['password2']

accounts/views.py
from django.shortcuts import render
from .forms import RegisterForm
# Create your views here.

def register(request):
    if request.method == 'POST':                                                                #회원 가입 정보가 전달
        user_form = RegisterForm(request.POST)                                                  #RegisterForm으로 유효성 검사
        if user_form.is_valid():
            new_user = user_form.save(commit=False)                                             #commit=False -> 데이터베이스에 넘기지 않음 객체만 만들어짐
            new_user.set_password(user_form.cleaned_data['password'])                           #비밀번호 지정 + 암호화
            new_user.save()                                                                     #실제로 데이터베이스에 저장
            return render(request, 'registration/register_done.html', {'new_user':new_user})

    else:
        user_form = RegisterForm()                                                              

    return render(request, 'registration/register.html',{'form':user_form})

photo/views.py
from django.shortcuts import render, redirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .models import Photo

from django.contrib.auth.mixins import LoginRequiredMixin       #권한 제한하는 건데 @login_required라는 decorator는 함수형 (def)뷰에서 사용 지금은 클래스 형 뷰->Mixin사용

class PhotoListView(LoginRequiredMixin,ListView):
     model = Photo
     template_name="photo/list.html"
    
class PhotoUploadView(LoginRequiredMixin,CreateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/upload.html'                         #사용할 템플릿

    def form_valid(self, form):                                 #업로드를 끝낸 후 이동할 페이지 호출할 메소드
        form.instance.author_id = self.request.user.id          #작성자는 현재 로그인한 사용자
        if form.is_valid():                                     #입력된 값을 검증
            form.instance.save()                                
            return redirect('/')                                #메인페이지로 이동
        else:
            return self.render_to_response({'form':form})       #이상이 있을시 작성된 내용을 그대로 작성 페이지에 표시

class PhotoDeleteView(LoginRequiredMixin,DeleteView):
    model = Photo
    success_url = '/'
    template_name = 'photo/delete.html'

class PhotoUpdateView(LoginRequiredMixin,UpdateView):
    model = Photo
    fields = ['photo','text']
    template_name = 'photo/update.html'

class PhotoDetailView(LoginRequiredMixin,DetailView):
    model = Photo
    template_name = 'photo/detail.html'

dstagram/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    {%load staticfiles%}
    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/blog/">
    <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="{%static 'css/blog.css'%}" rel="stylesheet">
    <title>Dstagrma{%block title%}{%endblock%}</title>
</head>
<body>
    <div class="container">
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center top-items">
                <div class="col-4 pt-1">
                    <a class="text-muted" href="{%url 'photo:photo_upload'%}">글쓰기</a>
                </div>
                <div class="col-4 text-center">
                    <a class="blog-header-logo text-dark" href="{%url 'photo:photo_list'%}">Dstagram</a>
                </div>
                {%if user.is_authenticated%}
                <div class="col-4 d-flex justify-content-end align-items-center">
                    <a class="text-muted" href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
                    </a>
                    <a class="btn btn-sm btn-outline-secondary" href="{%url 'logout'%}">Logout</a>
                </div>
                {%else%}
                <div class="col-4 d-flex justify-content-end align-items-center">
                    <a class="btn btn-sm btn-outline-secondary" href="{%url 'register'%}">Signup</a>
                    <a class="btn btn-sm btn-outline-secondary" href="{%url 'login'%}">Login</a>
                </div>
                {%endif%}
            </div>
        </header>
    {%block content%}
    {%endblock%}
    </div>
    
    <footer class="blog-footer">
        <p>&copy; 2019 SeonHo. Powered By Django 2.1.1</p>
        <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
        <p>
        <a href="#">Back to top</a>
        </p>
    </footer>
</body>
</html>

photo/templates/photo/delete.html
{%extends 'base.html'%}

{%block title%}-Delete{%endblock%}

{%block content%}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <div class="alert alert-info">
            Do you want to delete {{object}}?
        </div>
        <form action="" method="POST">
            {%csrf_token%}
            {{form.as_p}}
            <input type="submit" class="btn btn-danger" value="Confirm">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{%endblock%}

photo/templates/photo/detail.html
{%extends 'base.html'%}

{%block title%}{{object.text|truncatechars:10}}{%endblock%}

{%block content%}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <p><img src="{{object.photo.url}}" style="width:100%;"></p>
        <button type="button" class="btn btn-outline-primary btn-sm">
            {{object.author.username}}
        </button>
        <p>{{object.text|linebreaksbr}}</p>
        <a href="{% url 'photo:photo_delete' pk=object.id %}" class="bn btn-outline-danger btn-sm float-right">Delete</a>
        <a href="{% url 'photo:photo_update' pk=object.id %}" class="bn btn-outline-success btn-sm float-right">Update</a>
        {%load disqus_tags%}
        {%disqus_show_comments%}
    </div>
    <div class="col-md-2"></div>
</div>
{%endblock%}

photo/templates/photo/list.html
{%extends 'base.html'%}
{%block title%}-List{%endblock%}

{%block content%}
    {%for post in object_list%}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <p><img src="{{post.photo.url}}" style="width:100%;"></p>
            <button type="button" class="btn btn-xs btn-info">
                {{post.author.username}}
            </button>
            <p>{{post.text|linebreaksbr}}</p>
            <p class="text-right">
                <a href="{% url 'photo:photo_detail' pk=post.id%}" class="btn btn-xs btn-success">댓글달기</a>
            </p>
        </div>
        <div class="col-md-2"></div>
    </div>
    {%endfor%}
{%endblock%}

photo/templates/photo/photo_detail.html
{%extends 'base.html'%}

{%block title%}{{object.text|truncatechars:10}}{%endblock%}

{%block content%}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <p><img src="{{object.photo.url}}" style="width:100%;"></p>
        <button type="button" class="btn btn-outline-primary btn-sm">
            {{object.author.username}}
        </button>
        <p>{{object.text|linebreaksbr}}</p>
        <a href="{% url 'photo:photo_delete' pk=object.id %}" class="bn btn-outline-danger btn-sm float-right">Delete</a>
        <a href="{% url 'photo:photo_update' pk=object.id %}" class="bn btn-outline-success btn-sm float-right">Update</a>
        {%load disqus_tags%}
        {%disqus_show_comments%}
    </div>
    <div class="col-md-2"></div>
</div>
{%endblock%}

photo/templates/photo/update.html
{%extends 'base.html'%}

{%block title%}-Update{%endblock%}

{%block content%}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <form action="" method="POST" enctype="multipart/form-data">{%csrf_token%}
            {{form.as_p}}
            <input type="submit" class="btn btn-primary" value="Update">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{%endblock%}

photo/templates/photo/upload.html
{%extends 'base.html'%}
{%block title%}- Upload{%endblock%}

{%block content%}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <form action="" method="POST" enctype="multipart/form-data">{%csrf_token%}
            {{form.as_p}}
            <input type="submit" class="btn btn-primary" value="Upload">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{%endblock%}